app:
  env: "local"
  port: "8080"

limits:
  max_size_mb: 20

server:
  timeout: 4s
  idle_timeout: 60s

s3:
  endpoint: "minio:9000"
  access_key: "admin"
  secret_key: "supersecretpassword"
  bucket_name: "media"
  use_ssl: false

broker:
  address: "kafka:29092"
  queue_name: "pet-messages"
