apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
spec:
  type: NodePort # Открывает порт на самом сервере K8s 🖥️
  ports:
    - port: 9001       # Внутренний порт сервиса в кластере
      targetPort: 9001 # Порт внутри Пода, куда перенаправлять трафик
      nodePort: 32001  # Внешний порт на твоем ПК (диапазон 30000-32767)
  selector:
    app: minio-storage # Ищет Поды с такой же меткой 🔍